name: Teraflop CI

on: push
#   schedule:
#   - cron: '0 0 * * SUN'

jobs:
  test:
    name: Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ldc-latest
    - name: Install *nix Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get install --quiet -y libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev
    - name: Cache DUB Artifacts (Posix)
      # if: runner.os == 'Linux' || runner.os == 'macOS'
      uses: actions/cache@v2
      with:
        path: ~/.dub
        key: ${{ runner.os }}-dub-${{ hashFiles('**/dub.json') }}-${{ github.run_attempt }}
        restore-keys: |
          ${{ runner.os }}-dub-${{ hashFiles('**/dub.json') }}
    - name: Lint
      run: dub lint --config .dscanner.ini
    - name: Cache GLFW
      id: cache-glfw
      # if: runner.os == 'Linux'
      uses: actions/cache@v2
      with:
        path: lib/glfw-3.3.2
        key: ${{ runner.os }}-glfw
    - name: Test
      id: tests
      if: always() # Run tests even if lint step fails
      run: dub test --parallel --coverage
    - name: Upload Coverage to Codecov
      # Upload test coverage even if lint step fails
      if: success() || (steps.lint.outcome == 'failure' && steps.tests.outcome == 'success')
      run: bash <(curl -s https://codecov.io/bash)
