name: Teraflop CI

on: push
#   schedule:
#   - cron: '0 0 * * SUN'

jobs:
  test:
    name: Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ldc-latest
    # TODO: Consider disabling this `apt-get install` task to save time
    - name: Install *nix Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get install --quiet -y libglfw3 libglfw3-dev
    - name: Lint
      run: dub lint --config .dscanner.ini
    - name: Test
      run: make cover
    - name: Upload Coverage to Codecov
      if: success()
      run: bash <(curl -s https://codecov.io/bash)
    # - name: Upload Test Log Artifact on Failure
    #   uses: actions/upload-artifact@v1
    #   if: failure()
    #   with:
    #     name: Linux_Meson_Testlog
    #     path: build/meson-logs/testlog.txt
